export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const ADD_COINS = 'ADD_COINS';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const EDIT_EXPENSE = 'EDIT_EXPENSE';
export const SAVE_EXPENSE_EDIT = 'SAVE_EXPENSE_EDIT';
